# Generated by Django 3.0.3 on 2020-02-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Github',
        ),
    ]
