# Generated by Django 3.0.3 on 2020-02-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_user', '0002_auto_20200221_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github',
            old_name='last_modify_data',
            new_name='last_modify_date',
        ),
    ]
